### ISSUE TITLE
[side-question]: VSC extension to hide code with pattern

### ISSUE THREAD

**Issue by micalevisk** [estruyf/vscode-hide-comments#16]
Hi! well done!

I've a simple personal question to you: **from your experience on writting this extension, do you think that is feasible to write one that hide statements on typescript files that stars with `@Api`?**

eg:

![image](https://user-images.githubusercontent.com/13461315/144724531-2ce70c0c-e138-4312-b9d2-09f43573dd34.png)

I'm thinking about making an extension to show/hide the above statements in files ending with some pattern

The only extension I found that is almost like I wanted was this https://github.com/L3v3L/vs-focus which makes the code looks like this:
![image](https://user-images.githubusercontent.com/13461315/144724671-865e418e-5748-4cdd-a68b-9eaef9518c78.png)

**Comment by krisutofu** [comment]
I think, I have a related concern:
Usually, documentation comments make more sense to show than inline comments so it would be very useful to have an option which only removes non-documentation comments. The Java-Doc comments would be an example for a documentation comment or ```"""string"""``` comments in Python style.

**Comment by estruyf** [comment]
@micalevisk it depends a bit on which type of tokens these lines get, if they have generic code tokens and are not related to documentation/comments, it is a bit harder to achieve.

@krisutofu this would require a parser in order to discover the type of comments you write. Could indeed be related to the question from @micalevisk.
